server:
  port: 8610

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/laole?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1314521xjl
